spring.application.name=gerenciador-pedidos

spring.datasource.url=jdbc:postgresql://localhost:5432/gerenciador_pedidos
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true